---
title: "0529"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)

now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
now2()
```

```{r}
browseURL("https://www.ntpu.edu.tw")
```

```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#input-argumentoutput-value")
}
textbookURL()
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

#多個output值
```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  Qs <- a+b*P
  Qd <- c-d*P
  return(
    list(供給量=Qs,
        需求量=Qd,
        超額供給量=Qs-Qd)
  )
}
demand_supply_fun
```


#8.2 依條件執行 
if(邏輯條件){
  成立時執行
}
```{r}
a <- readline(prompt = "請輸入一個數字： ")

if(a < 0) {
  print("a為負值")
}
```

```{r}
a<-0
b<-1
supply_fun <- function(P,a,b){
  Qs <- a+b*P
  return(Qs)
}
supply_fun(P=-1,0,1)
```

```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```


```{r}
a <-  readline(prompt = "請輸入一個數字： ")

if(a < 0) {
  print("a為負值")
} else {
  print("a不為負值")
}
```

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```

```{r}
gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
    
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)}
  else{message("查無此學號")}
}
gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
fizzbuzz <- function(x){
  if(x%%15==0){print("fizzbuzz")}
  else if(x%%3==0){print("fizz")}
  else if(x%%5==0){print("buzz")}
  else{message("OTHER")}
}
fizzbuzz(33)
```


```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P必需大於等於",-a/b,"(即-a/b值)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
fizzbuzz <- function(input){
  
  if(input %% 15 == 0){print("fizzbuzz")}
  else if(input %% 5 == 0){print("buzz")}
  else if(input %% 3 == 0 ){print("fizz")}
  else{message("other situation")}
}
fizzbuzz(5)
fizzbuzz(30)
fizzbuzz(9)
fizzbuzz(7)
```

```{r}
a <- c(1,3,5)
a
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
```

#all()全部a都大於2/any()只要有一個a大於2
```{r}
a
a>2
all(a>2)
any(a>2)
```


```{r}
a <- c(1,3,5)
a
a>2 # 此邏輯條件產生三個值
if(any(a>2)) {
  print("a大於2")
}
```





















