---
title: '2019-03-27'
author: "林茂廷"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")

LisbonDateTime
```

```{r}
typeof(twDateTime)
as.double(twDateTime)
as.double(LisbonDateTime)
```

```{r}
twDateTime <- mdy_hms("03-27-2019 15:50:33")

twDateTime
```

```{r}
N <- ymd("2018-09-11")

N
```
```{r}
M <- mdy("March 3, 2019")

M
```

```{r}
as.integer(ymd("1970-01-01"))  
as.integer(ymd("1970-01-02"))  
as.integer(ymd("2019-03-11")) 
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```

```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
class(a+bL)
class(aL+bL)
```

```{r}
class(a-bL)
class(a*bL)
```

```{r}
a
a+4
a^b
a %% b
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime
twDateTime+1
```

```{r}
Test <- ymd("2019-08-11")
Test
Time <- ymd("2000-02-01")
Time

```

```{r}
Test-Time
```

```{r}
as.double(Test-Time)
```

```{r}
startingDate <- ymd("2000-02-17")
startingDate 
```

```{r}
startingDate + years(1)
```

```{r}
startingDate + dyears(1)
```

```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x >= y
x == y
x < y
```

```{r}
x = y

x
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3 == y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
x2
y2
x2 ==y2
```

```{r}
x2
is.na(x2)
```

```{r}
sum(x2)
sum(x2,na.rm=F)
sum(x2,na.rm=T)
```









