---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course,"經濟學")
```

```{r}
str_detect(course,"經濟學") #符合某元素=TRUE
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
```

```{r}
studentID
major <- str_sub(studentID,5,6) #第5到6碼
major
```

```{r}
year <- str_sub(studentID,2,4) #第2到4碼
year
```

#Join
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")

month
char1
day 
char2

str_c(month,char1,day,char2)
```

```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")

#"月"&"日"會自動重複(或用刮弧)
```

```{r}
month
day
str_c(month,day, sep="-") #sep自動分隔
```

```{r}
month
day
str_c(month,day, sep="月")
```

```{r}
dates <- c("3-11", "4-5",  "2-7")
date
str_split(dates,"-")
```

#取代
```{r}
dates
str_replace(dates,"-","月")
```

```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
username
reponame
```

```{r}
str_c("http://github.com",username,reponame,sep = "/")
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```

```{r}
ye <- str_sub(birthday,1,4)
mo <- str_sub(birthday,5,6)
da <- str_sub(birthday,7,8)  
answer <- str_c("西元",ye,"年",mo,"月",da,"日")
answer
```

#練習2
```{r}
民國年月<-c("099/01","099/02","099/03")
民國年月
```

```{r}
y <- str_sub(民國年月,1,3)
y
m <- str_sub(民國年月,5,6)
m
```

```{r}
turny <- as.integer(y)
turny
g <- 1911
wy <- turny+g
wy
```

```{r}
and <- str_c(wy,"/",m)
and
```

#Chapter6
```{r}
a<-c(1:3)  #1:3 = 1到3
typeof(a)
a
```

```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(aWithNames)
aWithNames
```

```{r}
b1<-list("a","b",c(1:10),TRUE)
typeof(b1)   
b1
```

```{r}
b2<-list(
  第一個="a",
  第二個="b",
  第三個=c(1:10),
  第四個=TRUE )
```

```{r}
b1
b2
```
















