---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

#Logical

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```


```{r}
# 加總向量內的所有元素值。
sum(aLogical)
```



```{r}
studentMajors <- factor(c("經濟系", "經濟系","法律系"))
```



```{r}
class(studentMajors0)
```

```{r}
studentMajors
```

```{r}
typeof(studentMajors)
```

```{r}
levels(studentMajors)
```

```{r}
as.integer(studentMajors)
```



```{r}
birthplace <- factor(c('台北市','台北市','台中市','台中市','台中市'))
birthplace
as.integer(birthplace)
```


```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```

```{r}
trueInteger 
```


```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

```{r}
typeof(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
levels(dtObject)
```





